### ISSUE TITLE
Item Show

### ISSUE THREAD

**Issue by jmejia** [applegrain/dinners_ready#10]
Background: I have an item

As a visitor
When I visit "/items/ITEM_ID"
Then I should see the title of the item
And I should see the description of the item
And I should see the price of the item
And I should see a button for "Add to Cart"

**Comment by jmejia** [comment]
Spacing with the navbar needs to be adjusted

**Comment by noobjey** [comment]
This was fixed in pull request #44, i forgot to close this card.
