### ISSUE TITLE
Viewing a single past order

### ISSUE THREAD

**Issue by jmejia** [applegrain/dinners_ready#18]
Background: An existing user that has one previous order

As an authenticated user
When I visit "/orders"
Then I should see my past order
And I should see a link to view that order
And when I click that link
Then I should see each item that was ordered with the quantity and line-item subtotals
And I should see links to each item's show page
And I should see the current status of the order (ordered, paid, cancelled, completed)
And I should see the total price for the order
And I should see the date/time that the order was submitted

#Moved these to separate cards
If the order was completed or cancelled
Then I should see a timestamp when the action took place

And if any of the items in the order were retired from the menu
Then they should still be able to access the item page
But they should not be able to add the item to their cart

**Comment by noobjey** [comment]
pulled out the last two expects to wait to feature test when the admin page is done

**Comment by noobjey** [comment]
Need to make sure the links for view work correctly on prod
