### ISSUE TITLE
Authenticated User

### ISSUE THREAD

**Issue by jmejia** [applegrain/dinners_ready#21]
As a visitor
When I visit "/"
Then I should see a link for "Login"
And when I click link "Create Account"
And I fill in USERNAME and PASSWORD
And I click "Create Account"
Then my current page should be "/dashboard"
And I should see a message in the navbar that says "Logged in as SOME_USER"
And I should see my profile information
And I should not see a link for "Login"
And I should see a link for "Logout"

When I click "Logout"
Then I should see see "Login"
And I should not see "Logout"

As a visitor
When I visit "/dashboard"
Then I should get a 404

**Comment by applegrain** [comment]
add happy path spec to make sure that a user is signed up (user_login_spec.rb)
test that their role is by default "default"
